x-logging: &default-logging
  options:
    max-size: "50m"

networks:
  subtensor:
    name: subtensor

services:
  btcli:
    image: ghcr.io/tensorplex-labs/dojo:main
    volumes:
      - ./:/app
      - $BITTENSOR_DIR:/root/.bittensor
    networks:
      - subtensor
    command: ["btcli"]
    tty: true
    stdin_open: true

  redis:
    image: redis/redis-stack-server:7.4.0-v0
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  postgres:
    image: postgres:15.7
    expose:
      - 5432
    healthcheck:
      test:
        # looks strange, but double $ (i.e. $$) for variable substitution
        ["CMD-SHELL", "pg_isready -h postgres-vali -U $${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging