services:
  dojo-ui-builder:
    build:
      context: ./dojo-ui
      dockerfile: ../Dockerfile-build-ui
    env_file: .env
    volumes:
      - ./dojo-ui-build:/build

  dojo-worker-api:
    build:
      context: ./dojo-worker-api
    env_file: .env
    volumes:
      # see workdir settings
      - ./.env:/dojo-api/.env:ro

  dojo-ui:
    build:
      context: ./dojo-ui
    env_file: .env
    depends_on:
      dojo-ui-builder:
        condition: service_completed_successfully
    volumes:
      - ./.env:/dojo-ui/.env:ro
      - ./dojo-ui-build:/dojo-ui:ro
      - ./dojo-ui/entrypoint.sh:/dojo-ui/entrypoint.sh:ro

  main-miner:
    build:
      context: .
      dockerfile: Dockerfile-miner
    env_file: .env
    command: python main_miner.py ${MINER_ARGS}
    depends_on:
      dojo-worker-api:
        condition: service_healthy
      dojo-ui:
        condition: service_healthy
    volumes:
      - $HOME/.bittensor:/root/.bittensor
