x-logging: &default-logging
  options:
    max-size: "50m"

networks:
  subtensor:
    name: subtensor

services:
  btcli:
    image: ghcr.io/tensorplex-labs/dojo:main
    volumes:
      - ./:/app
      - $BITTENSOR_DIR:/root/.bittensor
    networks:
      - subtensor
    command: ["btcli"]
    tty: true
    stdin_open: true

  redis:
    image: redis/redis-stack-server:7.4.0-v0
    expose:
      - 6379
    volumes:
      - redis-validator-volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  postgres:
    image: postgres:15.7
    # looks strange, but double $ (i.e. $$) for variable substitution
    command: >
      bash -c "
        export POSTGRES_USER=$${DB_USERNAME}
        export POSTGRES_PASSWORD=$${DB_PASSWORD}
        export POSTGRES_DB=$${DB_NAME}
        docker-entrypoint.sh postgres
      "
    expose:
      - 5432
    volumes:
      - postgres-validator-volume:/var/lib/postgresql/data
    healthcheck:
      test:
        # looks strange, but double $ (i.e. $$) for variable substitution
        ["CMD-SHELL", "pg_isready -h postgres-vali -U $${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging