name: Run Linter

on:
  push:
    branches: [ "junk/github-actions" ]
  pull_request:
    branches:
      - dev
      - staging
      - main
      - junk/github-actions

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.1.1      
        with:
          python-version: '3.11'    

      - uses: chartboost/ruff-action@v1
        with:
          args: --check .
          fix_args: --fix .

