name: Run Linter

on:
 pull_request:
   branches:
     - dev
     - staging
     - main
     - junk/github-actions

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@4.5.0

      - uses: chartboost/ruff-action@v1
        with:
          args: --check .
          fix_args: --fix .

