name: Dojo Build

on:
  push:
    branches: [ "junk/github-actions" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  release:
    name: Release
    runs-on: self-hosted
#    container: hoppr/semantic-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.12.0'
      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          branch: junk/github-actions
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

